/* eslint-disable */
/**
 * Auto-generated by scripts/generate-composition-registry.mjs — do not edit.
 * Add or change JSON in data/compositions/data/ and run `npm run dev` or `npm run build`.
 */

import raw_0 from './data/mere_dholna_3.0.json';
import raw_1 from './data/mere_dholna.json';
import raw_2 from './data/ninnnu_kori.json';
import raw_3 from './data/raghuvamsha_sudha.json';
import raw_4 from './data/sri_gananatha[en].json';

export interface CompositionRegistryEntry {
  slug: string;
  raw: unknown;
}

export const COMPOSITION_REGISTRY: CompositionRegistryEntry[] = [
  { slug: 'mere_dholna_3_0', raw: raw_0 as unknown },
  { slug: 'mere_dholna', raw: raw_1 as unknown },
  { slug: 'ninnnu_kori', raw: raw_2 as unknown },
  { slug: 'raghuvamsha_sudha', raw: raw_3 as unknown },
  { slug: 'sri_gananatha_en', raw: raw_4 as unknown },
];
